version: '3.7'

services:
  backend:
    build: ./app
    restart: always
    command: uvicorn app.main:app --reload --port 8000 --host 0.0.0.0 --proxy-headers
    volumes:
      - ./app/:/pegb/app
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - app/.env

  mysql:
    image: mysql:latest
    env_file:
      - database/.env
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend